version: 2

sources:
  - name: grocery_store
    description: Raw data from the store's CRM system containing data about customers, orders, order items and products.
    database: DBT_MARTIN
    schema: RAW
    tables:
      - name: customers
        description: Raw data containing customer details such as names, email and gender.
        columns:
          - name: id
            description: A unique identifier for each customer.
            tests:
              - unique
              - not_null
          - name: first_name
            description: The first name of the customer.
          - name: last_name
            description: The last name of the customer.
          - name: email
            description: The email address provided by the customer.
          - name: gender
            description: The gender indicated by the customer.
          - name: date_of_birth
            description: The date of birth as indicated by the customer.
      - name: orders
        description: A table containing raw data about the grocery store's orders.
        columns:
          - name: id
            description: A unique identifier for each order.
            tests:
              - unique
              - not_null
          - name: date
            description: The date on which the order was placed.
          - name: customer_id
            description: The ID of the customer who placed the order. Foreign key to `CUSTOMERS`.
          - name: status
            description: "{{doc('orders_status')}}"
      - name: order_items
        description: Raw data about the items in each order, including order ID, product ID and quantity.
        columns:
          - name: order_id
            description: The ID of the order that the item belongs to. Foreign key to `ORDERS`.
            tests:
              - relationships:
                  to: source('grocery_store', 'orders')
                  field: id
          - name: order_item_id
            description: The ID of the item within the current order.
          - name: product_id
            description: The ID of the product that the order item corresponds to. Foreign key to `PRODUCTS`.
            tests:
              - relationships:
                  to: source('grocery_store', 'products')
                  field: id
          - name: quantity
            description: The number of units of the product bought within the current order.
      - name: products
        description: Raw data about the products offered by the store, including name and price.
        columns:
          - name: id
            description: A unique identifier for each product.
            tests:
              - unique
              - not_null
          - name: name
            description: The name of the product.
          - name: price
            description: The price of the product.
          - name: category
            description: The category of the product.
